name: Submit an Issue 🐛
description: ...for bugs, installation problems, performance enhancements, etc.
title: "[HELP]: "
body:
  - type: markdown
    attributes:
      value: |
        Use this form to describe any issues you run into with the extension.
  - type: textarea
    id: issue
    attributes:
      label: What is your issue?
      placeholder: Describe the problem you're running into here.
    validations:
      required: true
